# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf096fdd5b3352078a3356dd60e6225036f80a3927c3880ce3f35ac046a9bdd99ba81c1d5e1673babd47516d251850be86b2c11a02792a25853d73e8bb0e9f62

test:
  secret_key_base: 1c095fdeb610fc1713cbc702148f27eca7aa9e0aefcb7e4208c71105badfeb2c2300a86ccf25c2f384e0692ae849fae93ce40c5eb92c691a55041171365bc104

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
